version: '2.1'
services:
  api:
    image: maven:3.6.1-jdk-11
    working_dir: /opt/src
    command: mvn dependency:go-offline spring-boot:run
    ports:
      - '3000:3000'
    volumes:
      - .:/opt/src
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=employeesystem